# Generated by Django 2.1.7 on 2019-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_auto_20190331_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='fin',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
