# Generated by Django 2.1.7 on 2019-03-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_auto_20190331_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hrm.Job', verbose_name='job'),
        ),
    ]
