# Generated by Django 2.1.7 on 2019-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_employee_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_len',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, default='not', max_length=16),
        ),
    ]
