# Generated by Django 2.1.7 on 2019-03-31 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_month_monthemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthemployee',
            name='day_1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_10',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_11',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_12',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_13',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_14',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_15',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_16',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_17',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_18',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_19',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_20',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_21',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_22',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_23',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_24',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_25',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_26',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_27',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_28',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_29',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_30',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_31',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_5',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_7',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_8',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='day_9',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
    ]
