# Generated by Django 2.1.7 on 2019-04-01 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0011_auto_20190331_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='last_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(28)]),
        ),
    ]
