# Generated by Django 2.1.7 on 2019-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_month_last_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthemployee',
            name='salary',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=7),
        ),
    ]
