# Generated by Django 2.1.7 on 2019-04-01 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0013_monthemployee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='hours',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(210)]),
        ),
    ]
