# Generated by Django 2.1.7 on 2019-04-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0014_month_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='social_insurance',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_insurance_len',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
