# Generated by Django 2.1.7 on 2019-04-02 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0015_auto_20190401_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='weekday',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='hours',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(210), django.core.validators.MinValueValidator(10)]),
        ),
    ]
