# Generated by Django 2.1.7 on 2019-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0016_auto_20190402_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthemployee',
            name='salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
