# Generated by Django 2.1.7 on 2019-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0017_auto_20190403_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthemployee',
            name='hours',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
