# Generated by Django 2.1.7 on 2019-04-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0018_monthemployee_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mid_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='quit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='quit_date',
            field=models.DateField(blank=True, null=True, verbose_name='quit date'),
        ),
    ]
