# Generated by Django 2.1.7 on 2019-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0019_auto_20190403_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthemployee',
            name='all_amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='monthemployee',
            name='rest',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
