# Generated by Django 2.1.7 on 2019-04-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_auto_20190403_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='give_bank_account',
            field=models.BooleanField(default=False),
        ),
    ]
