# Generated by Django 2.1.7 on 2019-04-13 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0021_auto_20190403_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(55), django.core.validators.MinValueValidator(1)])),
                ('sum', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(55), django.core.validators.MinValueValidator(1)])),
                ('year', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2055), django.core.validators.MinValueValidator(2001)])),
            ],
            options={
                'verbose_name': 'məzuniyyət',
                'verbose_name_plural': 'məzuniyyət',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departament', 'verbose_name_plural': 'Departamentlər'},
        ),
        migrations.AddField(
            model_name='employee',
            name='rest_days',
            field=models.IntegerField(default=21, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rest',
            name='emp',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hrm.Employee', verbose_name='employee'),
        ),
        migrations.AddField(
            model_name='rest',
            name='month',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hrm.Month', verbose_name='month'),
        ),
    ]
