# Generated by Django 2.1.7 on 2019-04-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0022_auto_20190413_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='extra_money',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
